services:
  - type: web
    name: stationeryhub
    runtime: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: stationeryhub-db
          property: connectionString
      - key: ASPNETCORE_ENVIRONMENT
        value: Production

databases:
  - name: stationeryhub-db
    plan: free
